-- 코드를 입력하세요
SELECT DISTINCT CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS CAR JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY  AS RENTAL ON CAR.CAR_ID = RENTAL.CAR_ID
WHERE CAR.CAR_TYPE='세단' AND DATE_FORMAT(RENTAL.START_DATE, '%m') = '10'
ORDER BY CAR.CAR_ID DESC;